// AUTO-GENERATED by tests/fixtures/generate_fixtures.py - do not edit.
// Recorded from the reference Python implementation in
// src/fragile/fractalai (asymmetric_rescale, l2_norm,
// FractalCloningOperator, FractalGas on the mock env).
#ifndef FRACTAL_GAS_FIXTURES_GENERATED_HPP
#define FRACTAL_GAS_FIXTURES_GENERATED_HPP

#include <cstdint>
#include <vector>

namespace fixtures {

const std::vector<float> kAsym_basic_in = {1.0f, 2.0f, 3.0f, 4.0f, 5.0f};
const std::vector<float> kAsym_basic_out = {0.282264411f, 0.531285644f, 1.0f, 1.49008536f, 1.81753552f};
const std::vector<float> kAsym_negatives_in = {-3.5f, 0.0f, 2.25f, -1.0f, 7.5f, -0.125f};
const std::vector<float> kAsym_negatives_out = {0.31284833f, 0.796156585f, 1.31664777f, 0.609669268f, 2.02015877f, 0.770035028f};
const std::vector<float> kAsym_all_equal_in = {2.5f, 2.5f, 2.5f, 2.5f};
const std::vector<float> kAsym_all_equal_out = {1.0f, 1.0f, 1.0f, 1.0f};
const std::vector<float> kAsym_single_in = {4.19999981f};
const std::vector<float> kAsym_single_out = {1.0f};
const std::vector<float> kAsym_random_in = {1.18328166f, -0.0630588084f, 0.990850925f, -0.506069422f, 2.9656179f, 0.850227654f, -1.26275587f, 0.521843374f, 1.32701015f, -1.1433351f, -0.263760269f, 0.986987233f, 1.59727705f, 0.555430174f, -1.55080926f, -0.0958748609f, 0.0851969197f, 0.848854601f, -0.00278463052f, -0.86044091f, 1.0578419f, -2.0101347f, 0.817853391f, -1.31935537f, 0.265762538f, 1.31194127f, -0.696871161f, 0.449431926f, 2.05218434f, 1.95540428f, 0.144385606f, -1.01533175f};
const std::vector<float> kAsym_random_out = {1.57431674f, 0.738763511f, 1.47584271f, 0.503486514f, 2.19951582f, 1.39720583f, 0.261557192f, 1.18519175f, 1.6420182f, 0.290037543f, 0.620963871f, 1.47376299f, 1.75810373f, 1.20905924f, 0.203842148f, 0.718076348f, 0.839907348f, 1.39640677f, 0.77832526f, 0.370499551f, 1.51123559f, 0.13697584f, 1.37819171f, 0.249053255f, 0.981978238f, 1.6351316f, 0.426844656f, 1.13171029f, 1.92740583f, 1.8937099f, 0.884054542f, 0.324016958f};
const std::vector<float> kAsym_large_scale_in = {1000000.0f, 2000000.0f, -500000.0f, 3300000.0f, 0.0f};
const std::vector<float> kAsym_large_scale_out = {0.900949657f, 1.4367094f, 0.338858038f, 1.87342167f, 0.469438493f};
struct AsymCase { const char* name; const std::vector<float>* in; const std::vector<float>* out; };
const std::vector<AsymCase> kAsymCases = {{"basic", &kAsym_basic_in, &kAsym_basic_out}, {"negatives", &kAsym_negatives_in, &kAsym_negatives_out}, {"all_equal", &kAsym_all_equal_in, &kAsym_all_equal_out}, {"single", &kAsym_single_in, &kAsym_single_out}, {"random", &kAsym_random_in, &kAsym_random_out}, {"large_scale", &kAsym_large_scale_in, &kAsym_large_scale_out}};

const int kL2N = 6;
const int kL2Dim = 5;
const std::vector<float> kL2Obs = {-0.820134521f, 0.395631164f, 0.898908496f, -1.38840389f, -0.166996017f, 0.285149962f, -0.641091526f, -0.893655419f, 0.926542997f, -0.535512209f, -1.1597203f, -0.460157156f, 0.708539069f, 1.01275539f, -1.38496137f, 0.503563881f, -0.0835282281f, -0.0234779324f, 0.174375355f, 2.2983427f, 0.95710218f, -0.661867559f, 1.39891839f, 1.40585291f, -1.40125084f, 1.29733586f, 1.64093328f, -1.05668414f, -0.261586726f, -0.25013262f};
const std::vector<int32_t> kL2Companions = {3, 0, 5, 1, 2, 4};
const std::vector<float> kL2Expected = {3.3693831f, 3.31730556f, 4.05949545f, 3.11645317f, 2.2700305f, 3.94386411f};

const int kCloneN = 10;
const int kCloneDim = 6;
const float kCloneDistCoef = 1.5f;
const float kCloneRewardCoef = 0.75f;
const bool kCloneUseCumulative = true;
const std::vector<float> kCloneObs = {-0.111718565f, -0.496590108f, 0.163073704f, -0.88168776f, 0.0539001934f, 0.668373704f, -0.0596576072f, -0.467497945f, -0.215252936f, 0.883961618f, -0.758416891f, -0.368867904f, -0.342393607f, -1.40197182f, 0.320647985f, -1.0218575f, 0.798832595f, -0.092287533f, -0.704919696f, -1.60236216f, 0.28909719f, 0.489870846f, -0.385274619f, -0.712034583f, -0.170613497f, -1.45943868f, 0.220659077f, 0.246252075f, -1.32481194f, 0.696980536f, -0.66305387f, 1.21575689f, -1.49487579f, 0.88096112f, -1.17864752f, -0.933995008f, -0.567545474f, -0.27722767f, -2.18339777f, 0.366826355f, 0.938027382f, 0.00781648513f, -0.313860476f, -1.15670431f, -0.297135472f, -1.53797054f, -1.02484977f, -0.378061563f, 0.925742388f, 0.924696088f, 0.182535648f, -0.0736977607f, 1.13335586f, 0.850423515f, 1.05338991f, 0.369178504f, 0.0627958626f, -0.329674631f, -1.79696834f, 0.872817755f};
const std::vector<float> kCloneCumRewards = {2.42615533f, 0.0650987551f, 3.12391901f, 0.21073772f, 1.73896432f, 0.17973122f, 0.544690728f, 2.03902769f, 0.770174623f, 5.45666361f};
const std::vector<float> kCloneStepRewards = {0.211088777f, 0.337156564f, 0.663804233f, 1.03968239f, 1.84336233f, 0.658800423f, -0.234917164f, -0.0306136236f, 1.74617505f, -0.0721850172f};
const std::vector<uint8_t> kCloneAlive = {1, 1, 0, 1, 1, 1, 1, 0, 1, 1};
const std::vector<int32_t> kCloneFitCompanions = {3, 1, 9, 1, 8, 9, 3, 9, 4, 8};
const std::vector<int32_t> kCloneCloneCompanions = {1, 5, 9, 1, 3, 9, 1, 9, 3, 6};
const std::vector<float> kCloneUniforms = {0.178024471f, 0.644151568f, 0.589379072f, 0.587157547f, 0.964275897f, 0.776785672f, 0.844651401f, 0.719545007f, 0.710142136f, 0.413028955f};
const std::vector<float> kCloneExpectedVr = {0.803339243f, 0.0148109542f, 2.88430142f, 0.115969889f, 2.04734302f, 0.899664879f, 0.956560194f, 1.30335999f, 1.33924544f, 2.41290569f};
const std::vector<float> kCloneExpectedProbs = {-0.98156321f, 59.743206f, -0.163434982f, -0.872286201f, -0.943355918f, 1.68200505f, -0.984516442f, 0.851296425f, -0.913406551f, -0.603565037f};
const std::vector<uint8_t> kCloneExpectedWillClone = {0, 1, 1, 0, 0, 1, 0, 1, 0, 0};

const int kRunN = 8;
const int kRunIters = 5;
const int kRunNElite = 2;
const std::vector<std::vector<int32_t>> kRunFitCompanions = {{5, 6, 7, 4, 3, 2, 1, 0}, {7, 3, 5, 1, 0, 6, 2, 4}, {7, 2, 1, 6, 4, 5, 0, 3}, {4, 1, 6, 2, 2, 2, 2, 1}, {2, 2, 2, 2, 2, 2, 2, 2}};
const std::vector<std::vector<int32_t>> kRunCloneCompanions = {{6, 3, 7, 4, 2, 1, 0, 5}, {2, 4, 5, 0, 1, 6, 7, 3}, {5, 0, 4, 1, 6, 7, 3, 2}, {6, 6, 6, 4, 6, 2, 4, 4}, {2, 2, 2, 2, 2, 2, 2, 2}};
const std::vector<std::vector<float>> kRunUniforms = {{0.810787678f, 0.77838254f, 0.236236155f, 0.289859474f, 0.332811773f, 0.909214914f, 0.250167489f, 0.622439325f}, {0.023976028f, 0.600348592f, 0.869141281f, 0.313215077f, 0.171209276f, 0.2083655f, 0.677568972f, 0.649604499f}, {0.64087534f, 0.186021507f, 0.597449899f, 0.158411205f, 0.15445596f, 0.847422898f, 0.358400166f, 0.662942231f}, {0.937633216f, 0.904966891f, 0.242878258f, 0.323908627f, 0.0402473807f, 0.200976789f, 0.0241808891f, 0.562949657f}, {0.698294878f, 0.47486794f, 0.175478339f, 0.313766003f, 0.903649449f, 0.830723584f, 0.82957238f, 0.278697789f}};
const std::vector<std::vector<int32_t>> kRunActions = {{1, 3, 1, 0, 1, 0, 2, 0}, {1, 0, 1, 3, 2, 3, 0, 3}, {3, 3, 2, 3, 3, 2, 1, 2}, {3, 1, 3, 3, 2, 2, 2, 3}, {3, 2, 3, 1, 3, 1, 1, 3}};
const std::vector<std::vector<int32_t>> kRunDts = {{2, 1, 2, 4, 3, 4, 4, 2}, {3, 1, 1, 1, 1, 1, 2, 4}, {1, 1, 2, 3, 2, 2, 1, 2}, {2, 1, 1, 1, 2, 4, 2, 1}, {2, 1, 2, 1, 4, 1, 1, 2}};
const std::vector<std::vector<float>> kRunExpectedRewards = {{0.0399999991f, 0.24000001f, 0.0399999991f, -0.360000014f, 0.0599999987f, -0.360000014f, 0.519999981f, -0.180000007f}, {0.699999988f, 0.0299999975f, 0.099999994f, 0.879999995f, 0.25f, 0.879999995f, 0.459999979f, 0.800000012f}, {1.27999997f, 1.27999997f, 0.419999987f, 1.75999999f, 0.819999993f, 1.24000001f, 1.05999994f, 1.24000001f}, {1.71999991f, 1.5f, 0.779999971f, 1.23000002f, 1.25f, 1.05999994f, 1.25f, 1.23000002f}, {1.41999996f, 1.06999993f, 1.41999996f, 0.959999979f, 1.89999998f, 0.959999979f, 0.959999979f, 1.41999996f}};
const std::vector<std::vector<float>> kRunExpectedVr = {{1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f}, {3.46793723f, 0.518678308f, 0.300734639f, 0.111231215f, 1.25059724f, 0.489219964f, 2.98158765f, 0.381414264f}, {0.769864798f, 2.14980412f, 0.824209929f, 0.769864798f, 0.272217959f, 0.46651724f, 0.200297162f, 1.48973048f}, {2.88162327f, 0.146731675f, 0.344257325f, 3.75157046f, 0.735510588f, 1.2185173f, 0.197476804f, 0.38332206f}, {3.94409776f, 2.53550744f, 0.0611743368f, 0.320222229f, 0.624058902f, 1.94551778f, 0.624058902f, 0.320222229f}};
const std::vector<std::vector<int32_t>> kRunExpectedWillClone = {{0, 0, 0, 0, 0, 0, 0, 0}, {0, 1, 0, 1, 0, 1, 0, 0}, {0, 0, 0, 1, 0, 1, 1, 0}, {1, 0, 0, 1, 0, 1, 1, 1}, {1, 1, 0, 1, 1, 1, 1, 1}};
const std::vector<float> kRunExpectedMaxReward = {0.519999981f, 0.879999995f, 1.75999999f, 1.75999999f, 1.89999998f};
const std::vector<float> kRunFinalObservations = {24.0f, 4.0f, 5.0f, 19.0f, 3.5f, 5.0f, 24.0f, 4.0f, 5.0f, 18.0f, 3.5f, 5.0f, 32.0f, 5.0f, 5.0f, 18.0f, 3.5f, 5.0f, 18.0f, 3.5f, 5.0f, 24.0f, 4.0f, 5.0f};

}  // namespace fixtures

#endif  // FRACTAL_GAS_FIXTURES_GENERATED_HPP