// Generated by generate_fixtures.py from Python operators; do not hand edit.
#pragma once
#include <vector>
namespace optimization_fixture {
inline const std::vector<double> positions = {-1, 0.5, 0.20000000298023224, -0.30000001192092896, 1, 1.2000000476837158, 2, -0.60000002384185791};
inline const std::vector<double> velocities = {0.10000000149011612, 0.20000000298023224, -0.20000000298023224, 0.30000001192092896, 0.40000000596046448, -0.5, -0.60000002384185791, 0.69999998807907104};
inline const std::vector<double> objectives = {0.0625, 0.0065000005997717381, 0.12200000137090683, 0.21800000965595245};
inline const std::vector<double> fitness_global = {0.8601565957069397, 1.0493314266204834, 1.5224068164825439, 0.73651903867721558};
inline const std::vector<double> fitness_local = {0.77413249015808105, 1.004328727722168, 1.5605757236480713, 0.32530114054679871};
inline const std::vector<double> fitness_periodic = {0.8601565957069397, 1.0493314266204834, 1.5224068164825439, 0.73651903867721558};
inline const std::vector<double> wrapped_positions = {-1, 0.5, 0.20000000298023224, -0.30000001192092896, -1, -0.79999995231628418, 0, -0.60000002384185791};
inline const std::vector<double> cloned_x = {-1, 0.5, 0.20000000298023224, -0.30000001192092896, 1, 1.2000000476837158, 0.97104072570800781, 1.1710407733917236};
inline const std::vector<double> cloned_v = {0.10000000149011612, 0.20000000298023224, -0.20000000298023224, 0.30000001192092896, 0.099999994039535522, -0.14000001549720764, -0.30000001192092896, 0.34000000357627869};
inline const std::vector<double> clone_mask = {0, 0, 0, 1};
inline const std::vector<double> baoab_x = {-0.9995540976524353, 0.50143444538116455, 0.1974518746137619, -0.29756554961204529, 1.0034239292144775, 1.1944588422775269, 1.9934588670730591, -0.59358006715774536};
inline const std::vector<double> baoab_v = {-0.010820910334587097, 0.086887761950492859, -0.30962422490119934, 0.18688727915287018, 0.2847951352596283, -0.60822832584381104, -0.70822781324386597, 0.58399677276611328};
inline const std::vector<double> companions_uniform = {0, 0, 0, 0};
inline const std::vector<double> periodic_companions_uniform = {0, 0, 0, 0};
inline const std::vector<double> companions_softmax = {1, 2, 1, 1};
inline const std::vector<double> periodic_companions_softmax = {2, 2, 1, 1};
inline const std::vector<double> companions_cloning = {1, 2, 1, 1};
inline const std::vector<double> periodic_companions_cloning = {2, 2, 1, 1};
inline const std::vector<double> companions_random_pairing = {3, 2, 1, 0};
inline const std::vector<double> periodic_companions_random_pairing = {3, 2, 1, 0};
inline const std::vector<double> companions_greedy_pairing = {1, 0, 3, 2};
inline const std::vector<double> periodic_companions_greedy_pairing = {2, 3, 0, 1};
} // namespace optimization_fixture
