"""Generate operator fixtures by executing the Python reference with injected draws.

Run with ``uv run python fractal-gas-web/tests/optimization/generate_fixtures.py``.
The C++ fixture RNG returns uniform .37 and integer 0; its Fisher-Yates
permutation for four rows is [1, 2, 3, 0]. No seeded cross-language RNG parity
is assumed.
"""

import math
from pathlib import Path
from unittest.mock import patch

import torch

from fragile.fractalai.bounds import TorchBounds
from fragile.fractalai.core.benchmarks import QuadraticWell
from fragile.fractalai.core.cloning import clone_walkers
from fragile.fractalai.core.companion_selection import CompanionSelection
from fragile.fractalai.core.euclidean_gas import SwarmState
from fragile.fractalai.core.fitness import compute_fitness
from fragile.fractalai.core.kinetic_operator import KineticOperator


def main():
    x = torch.tensor([[-1.0, 0.5], [0.2, -0.3], [1.0, 1.2], [2.0, -0.6]])
    v = torch.tensor([[0.1, 0.2], [-0.2, 0.3], [0.4, -0.5], [-0.6, 0.7]])
    alive = torch.ones(4, dtype=torch.bool)
    companions = torch.tensor([1, 0, 3, 2])
    potential = QuadraticWell(dims=2)
    rewards = -potential(x)
    u = float(torch.tensor(0.37))
    gaussian = math.sqrt(-2 * math.log(u)) * math.cos(2 * math.pi * u)
    outputs = {"positions": x, "velocities": v, "objectives": -rewards}
    for rho in [None, 1.5]:
        fit, _ = compute_fitness(x, v, rewards, alive, companions, lambda_alg=0.2, rho=rho)
        outputs["fitness_global" if rho is None else "fitness_local"] = fit
    fit = outputs["fitness_global"]
    bounds = TorchBounds(low=torch.full((2,), -1.0), high=torch.full((2,), 1.0))
    outputs["fitness_periodic"], _ = compute_fitness(
        x, v, rewards, alive, companions, lambda_alg=0.2, bounds=bounds, pbc=True
    )
    outputs["wrapped_positions"] = bounds.apply_pbc_to_out_of_bounds(x)
    with (
        patch("torch.rand", side_effect=lambda *shape, **_kw: torch.full(shape, u)),
        patch("torch.randn", side_effect=lambda *shape, **_kw: torch.full(shape, gaussian)),
    ):
        cx, cv, _, info = clone_walkers(
            x,
            v,
            fit,
            companions,
            alive,
            p_max=1,
            epsilon_clone=1e-6,
            sigma_x=0.03,
            alpha_restitution=0.4,
        )
        outputs.update(cloned_x=cx, cloned_v=cv, clone_mask=info["will_clone"])
        kinetic = KineticOperator(
            gamma=0.8,
            beta=1.2,
            delta_t=0.01,
            potential=potential,
            integrator="baoab",
            use_anisotropic_diffusion=False,
            use_viscous_coupling=False,
            device=torch.device("cpu"),
            dtype=torch.float32,
        )
        state = kinetic.apply(SwarmState(x.clone(), v.clone()))
        outputs.update(baoab_x=state.x, baoab_v=state.v)

    def multinomial(probs, num_samples=1):
        if probs.ndim == 1:
            return torch.tensor([int(torch.searchsorted(probs.cumsum(0), u))])
        return (probs.cumsum(1) < u).sum(1, keepdim=True)

    with (
        patch("torch.multinomial", side_effect=multinomial),
        patch(
            "torch.randint",
            side_effect=lambda _low, _high, size, **_kw: torch.zeros(size, dtype=torch.long),
        ),
        patch("torch.randperm", return_value=torch.tensor([1, 2, 3, 0])),
    ):
        for method in ["uniform", "softmax", "cloning", "random_pairing", "greedy_pairing"]:
            selector = CompanionSelection(method=method, epsilon=2, lambda_alg=0.2)
            outputs[f"companions_{method}"] = selector(x=x, v=v, alive_mask=alive)
            outputs[f"periodic_companions_{method}"] = selector(
                x=x, v=v, alive_mask=alive, bounds=bounds, pbc=True
            )
    lines = [
        "// Generated by generate_fixtures.py from Python operators; do not hand edit.",
        "#pragma once",
        "#include <vector>",
        "namespace optimization_fixture {",
    ]
    for name, values in outputs.items():
        values = values.flatten().tolist()
        literal = ", ".join(format(float(value), ".17g") for value in values)
        lines.append(f"inline const std::vector<double> {name} = {{{literal}}};")
    lines.append("} // namespace optimization_fixture")
    Path(__file__).with_name("fixtures.hpp").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
