###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Guillem Duran-Ballester'
autodoc_typehints = 'description'
autosectionlabel_maxdepth = 3
autosectionlabel_prefix_document = True
bibtex_bibfiles = ['references.bib', 'source/2_fractal_gas/references.bib']
bibtex_default_style = 'alpha'
bibtex_reference_style = 'author_year'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2025'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', '.venv', 'Thumbs.db', '_build', 'archive/**', 'extract_sections.py', 'index.md.bak', 'migrations/**', 'node_modules']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx.ext.autodoc', 'sphinx.ext.doctest', 'sphinx.ext.todo', 'sphinx.ext.coverage', 'sphinx.ext.viewcode', 'sphinx.ext.napoleon', 'sphinx.ext.autosectionlabel', 'sphinx.ext.autodoc.typehints', 'sphinx.ext.githubpages', 'sphinxcontrib.mermaid', 'sphinx_proof', 'fragile_proof_types', 'fragile_proofs', 'fragile_redirects', 'sphinx_tippy', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = True
external_toc_path = '_toc.yml'
html_baseurl = 'https://fragiletech.github.io/fragile/docs/theory/'
html_css_files = ['custom.css']
html_favicon = 'favicon.png'
html_js_files = ['prompt-downloads.js', 'expert-mode.js']
html_logo = 'logo.png'
html_sourcelink_suffix = ''
html_static_path = ['_static_theory', '_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'search_bar_text': 'Search this book...', 'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': '', 'jupyterhub_url': '', 'thebe': False, 'colab_url': '', 'deepnote_url': ''}, 'path_to_docs': '', 'repository_url': 'https://github.com/FragileTech/fragile', 'repository_branch': 'main', 'extra_footer': '', 'home_page_in_toc': True, 'announcement': '', 'analytics': {'google_analytics_id': '', 'plausible_analytics_domain': '', 'plausible_analytics_url': 'https://plausible.io/js/script.js'}, 'use_repository_button': False, 'use_edit_page_button': False, 'use_issues_button': False}
html_title = 'Lectures on Algorithmic Geometrodynamics'
latex_engine = 'pdflatex'
myst_enable_extensions = ['amsmath', 'colon_fence', 'deflist', 'dollarmath', 'html_admonition', 'html_image', 'linkify', 'replacements', 'smartquotes', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
napoleon_google_docstring = True
napoleon_numpy_docstring = False
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = ['source/1_agent/08_multiagent/04_constants_check.ipynb']
nb_execution_in_temp = False
nb_execution_mode = 'off'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
release = '0.2.0'
suppress_warnings = ['bibtex.duplicate_citation', 'bibtex.duplicate_label', 'myst.directive_option']
tippy_enable_doitips = True
tippy_enable_mathjax = True
tippy_enable_wikitips = True
tippy_props = {'placement': 'auto-start', 'maxWidth': 500, 'interactive': True, 'theme': 'material'}
use_jupyterbook_latex = True
use_multitoc_numbering = True
version = '0.2.0'
